# Setup
title: Spangle
logo: "/public/images/sina-sohangir.png"
tagline: "Smart landing page"
description: "Personal Blog"
url: https://sinaso.github.io/
baseurl: "/"
paginate: 5

# About and contact
author:
  name: "Sina Sohangir"
  email: ""
  x: https://x.com/sohangir
  linkedin: https://linkedin.com/in/sohangir

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version: 1.0.0
